---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-apm-agent-java-release
  description: Buildkite Release pipeline for apm-agent-java
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/apm-agent-java-release
  tags:
    - buildkite
    - gpg-sign
    - maven-central
spec:
  type: buildkite-pipeline
  owner: group:apm-agent-java
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: apm-agent-java-release
    spec:
      repository: elastic/apm-agent-java
      pipeline_file: ".buildkite/release.yml"
      provider_settings:
        trigger_mode: none
      teams:
        apm-agent-java:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots-automation:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-apm-agent-java-snapshot
  description: Buildkite Snapshot pipeline for apm-agent-java
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/apm-agent-java-snapshot
  tags:
    - buildkite
    - gpg-sign
    - maven-central
spec:
  type: buildkite-pipeline
  owner: group:apm-agent-java
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: apm-agent-java-snapshot
    spec:
      repository: elastic/apm-agent-java
      pipeline_file: ".buildkite/snapshot.yml"
      provider_settings:
        trigger_mode: none
      teams:
        apm-agent-java:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots-automation:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-apm-agent-java-load-testing
  description: Buildkite Load Testing Pipeline for apm-agent-java
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/apm-agent-java-load-testing
spec:
  type: buildkite-pipeline
  owner: group:apm-agent-java
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: apm-agent-java-load-testing
    spec:
      repository: elastic/apm-agent-java
      pipeline_file: ".buildkite/load-testing.yml"
      provider_settings:
        trigger_mode: none
      teams:
        apm-agent-java:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots-automation:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-apm-agent-java-opentelemetry-benchmark
  description: Buildkite Opentelemetry Benchmark for apm-agent-java
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/apm-agent-java-opentelemetry-benchmark
  tags:
    - buildkite
spec:
  type: buildkite-pipeline
  owner: group:apm-agent-java
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: apm-agent-java-opentelemetry-benchmark
    spec:
      repository: elastic/apm-agent-java
      pipeline_file: ".buildkite/opentelemetry-benchmark.yml"
      default_branch: main
      provider_settings:
        trigger_mode: none
      teams:
        apm-agent-java:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots-automation:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      schedules:
        Weekly Benchmark on main Branch:
          cronline: "@weekly"
          message: "Run the quick benchmark weekly."

---
# A Component for the release GitHub action
#
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: apm-agent-java-release
  description: GitHub action to run the release process for the APM Agent Java
  annotations:
    backstage.io/source-location: url:https://github.com/elastic/apm-agent-java/blob/main/.github/workflows/release.yml
    github.com/project-slug: elastic/apm-agent-java
    github.com/team-slug: elastic/apm-agent-java
  tags:
    - aws-lambda
    - github
    - gpg-sign
    - maven-central
    - release
    - user:obltmachine
  links:
    - title: GitHub action
      url: https://github.com/elastic/apm-agent-java/actions/workflows/release.yml
spec:
  type: github-actions
  owner: group:apm-agent-java
  lifecycle: production
  dependsOn:
    - "system:github-actions"
    - "user:obltmachine"

---
# A Component for the snapshot GitHub action
#
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: apm-agent-java-snapshot
  description: GitHub action to run the snapshot process for the APM Agent Java
  annotations:
    backstage.io/source-location: url:https://github.com/elastic/apm-agent-java/blob/main/.github/workflows/snapshot.yml
    github.com/project-slug: elastic/apm-agent-java
    github.com/team-slug: elastic/apm-agent-java
  tags:
    - github
    - gpg-sign
    - maven-central
    - snapshot
    - user:obltmachine
  links:
    - title: GitHub action
      url: https://github.com/elastic/apm-agent-java/actions/workflows/snapshot.yml
spec:
  type: github-actions
  owner: group:apm-agent-java
  lifecycle: production
  dependsOn:
    - "system:github-actions"
    - "user:obltmachine"

---
# A Component for the microbenchmark GitHub action
#
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: apm-agent-java-microbenchmark
  description: GitHub action to run the microbenchmark process for the APM Agent Java
  annotations:
    backstage.io/source-location: url:https://github.com/elastic/apm-agent-java/blob/main/.github/workflows/microbenchmark.yml
    github.com/project-slug: elastic/apm-agent-java
    github.com/team-slug: elastic/apm-agent-java
  tags:
    - github
    - user:obltmachine
  links:
    - title: GitHub action
      url: https://github.com/elastic/apm-agent-java/actions/workflows/microbenchmark.yml
spec:
  type: github-actions
  owner: group:apm-agent-java
  lifecycle: production
  dependsOn:
    - "system:github-actions"
    - "user:obltmachine"
