FROM docker.elastic.co/wolfi/chainguard-base:latest@sha256:382a0ce72c89e573e5491339112cf7acc1a7d91357805b2cf77d6eb74782b948
RUN mkdir /usr/agent
ARG JAR_FILE
ARG HANDLER_FILE
COPY ${JAR_FILE} /usr/agent/elastic-apm-agent.jar
COPY ${HANDLER_FILE} /usr/agent/elastic-apm-handler
RUN chmod +x /usr/agent/elastic-apm-handler
RUN ln -s /usr/agent/elastic-apm-agent.jar /javaagent.jar
