steps:
  - label: Pre-flight
    # https://badge.buildkite.com/docs/agent/v3/cli-env
    command: |
      result=$$(.ci/load/scripts/start.sh)
      buildkite-agent env set "SESSION_TOKEN=$${session_token}"
    env:
      ORCH_URL: "https://obs-load-orch.app.elstc.co"
    artifact_paths:
      - ".ci/load/**"
  - wait

  - label: test
    command: |
      buildkite-agent env get SESSION_TOKEN
      echo "$${SESSION_TOKEN}"
