steps:
  - label: Pre-flight
    # https://badge.buildkite.com/docs/agent/v3/cli-env
    command: .ci/load/scripts/start.sh
    env:
      ORCH_URL: "https://obs-load-orch.app.elstc.co"
    artifact_paths:
      - ".ci/load/**"
  - wait

  - label: test
    command: |
      buildkite-agent env get SESSION_TOKEN
      echo "${SESSION_TOKEN}"
