steps:
  - label: Pre-flight
    # https://badge.buildkite.com/docs/agent/v3/cli-env
    command: |            
      result=$(.ci/load/scripts/start.sh)
      echo $result
    #      buildkite-agent env set "SESSION_TOKEN=${result}"
    artifact_paths:
      - ".ci/load/**"
