env:
  REPO: "apm-agent-java"
  AGENT_BASE_DIR: "src/apm-agent-java"
  APP: "spring-petclinic"
  APP_BASE_DIR: "src/spring-petclinic"
  APM_VERSION: ${APM_VERSION:-main}
  JVM_VERSION: ${JVM_VERSION:-zulu-17.0.8.1-linux} # This needs to at least JDK 17, otherwise building the petclinic app will fail
steps:
  - label: Pre-flight
    # https://badge.buildkite.com/docs/agent/v3/cli-env
    command: |
      session_token=$$(.ci/load/scripts/start.sh)
      buildkite-agent meta-data set "session-token" "$${session_token}"
    env:
      ORCH_URL: "https://obs-load-orch.app.elstc.co"

#      SESSION_TOKEN=$$(buildkite-agent meta-data get "session-token")

  - wait

  - label: Build agent
    key: build-agent
#    agents:
#      queue: observability-microbenchmarks
    command: .buildkite/scripts/build-agent.sh
    artifact_paths:
      - elastic-apm-agent.jar
    agents:
      memory: "2G"

  - label: Download agent
    depends_on:
      - build-agent
#    agents:
#      queue: observability-microbenchmarks
    command: |
      buildkite-agent artifact search "*" -format "%p\n"
      buildkite-agent artifact download "elastic-apm-agent.jar" .
      ls -al

  - label: Build test application
#    agents:
#      queue: observability-microbenchmarks
    command: .buildkite/scripts/build-test-application.sh
