steps:
  - label: Pre-flight
    # https://badge.buildkite.com/docs/agent/v3/cli-env
    command: |
      session_token=$$(.ci/load/scripts/start.sh)
      buildkite-agent meta-data set "session-token" "$${session_token}"
    env:
      ORCH_URL: "https://obs-load-orch.app.elstc.co"
    artifact_paths:
      - ".ci/load/**"
  - wait

  - label: test
    command: |
      SESSION_TOKEN=$$(buildkite-agent meta-data get "session-token")
      echo "$${SESSION_TOKEN}"
