env:
  REPO: "apm-agent-java"
  AGENT_BASE_DIR: "src/apm-agent-java"
  APM_VERSION: ${APM_VERSION:-"main"}

steps:
  - label: Pre-flight
    # https://badge.buildkite.com/docs/agent/v3/cli-env
    command: |
      session_token=$$(.ci/load/scripts/start.sh)
      buildkite-agent meta-data set "session-token" "$${session_token}"
    env:
      ORCH_URL: "https://obs-load-orch.app.elstc.co"

#      SESSION_TOKEN=$$(buildkite-agent meta-data get "session-token")

  - wait

  - label: Build agent
    key: build-agent
    agents:
      queue: observability-microbenchmarks
    command: |
      current_dir=$$(pwd)
      git clone "https://github.com/elastic/$${REPO}.git" "$${AGENT_BASE_DIR}"
      cd "$${AGENT_BASE_DIR}"
      # git checkout $${APM_VERSION}
      ./mvnw -X --batch-mode clean package -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.sources.skip=true
      cp -v $$(find ./elastic-apm-agent/target -name '*.jar' | grep -v sources | grep -v original | grep -v javadoc) "$${current_dir}/elastic-apm-agent.jar"
      buildkite-agent artifact upload "elastic-apm-agent.jar"
