env:
  REPO: "apm-agent-java"
  AGENT_BASE_DIR: "src/apm-agent-java"
  APM_VERSION: ${APM_VERSION:-main}

steps:
  - label: Pre-flight
    # https://badge.buildkite.com/docs/agent/v3/cli-env
    command: |
      session_token=$$(.ci/load/scripts/start.sh)
      buildkite-agent meta-data set "session-token" "$${session_token}"
    env:
      ORCH_URL: "https://obs-load-orch.app.elstc.co"

#      SESSION_TOKEN=$$(buildkite-agent meta-data get "session-token")

  - wait

  - label: Build agent
    key: build-agent
    agents:
      queue: observability-microbenchmarks
    command: .buildkite/scripts/build-agent.sh

  - label: Download agent
    depends_on:
      - build-agent
    agents:
      queue: observability-microbenchmarks
    command: |
      buildkite-agent artifact search "*" -format "%p\n"
      buildkite-agent artifact download "elastic-apm-agent.jar" .
      ls -al
