steps:
  - label: "Run the opentelemetry-benchmark"
    commands: .buildkite/scripts/opentelemetry-benchmark.sh
    agents:
      queue: observability-microbenchmarks
    artifact_paths:
      - "**/build/reports/tests/test/classes/io.opentelemetry.OverheadTests.html"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'
