steps:
  - label: "Run the opentelemetry-benchmark"
    commands: .buildkite/scripts/opentelemetry-benchmark.sh
    agents:
      queue: observability-microbenchmarks
    artifact_paths:
      - "**/build/reports/tests/test/classes/io.opentelemetry.OverheadTests.html"
      - "**/build/reports/tests/test/index.html"
      - "**/hs_err_pid*.log"
      - "output.json"
    env: ## https://buildkite.com/docs/agent/v3/securing#forcing-clean-checkouts
      BUILDKITE_CLEAN_CHECKOUT: true
