agents:
  provider: "gcp"
  image: "family/apm-agent-java-ubuntu-2204"

steps:
  - label: "Run the release"
    key: "release"
    commands: .ci/release.sh
    artifact_paths:
      - "release.txt"
      - "**/target/*"

notify:
  - slack: "#apm-agent-java"
    # skip slack messages if no failures and dry-run mode
    if: 'build.state != "passed" && build.env("dry_run") == "false"'
