agents:
  provider: "gcp"

steps:
  - label: "Run the snapshot"
    key: "release"
    commands:
      - echo "hello"
      - glcoud --version
#    artifact_paths:
#      - "release.txt"
#      - "**/target/*"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'
