agents:
  provider: "gcp"

steps:
  - label: "Run the snapshot"
    key: "release"
    commands: .ci/release.sh
    artifact_paths:
      - "release.txt"
      - "**/target/*"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'
