agents:
  provider: "gcp"
  #image: "family/apm-agent-java-ubuntu-2204"

steps:
  - label: "Run the release"
    key: "release"
    commands: .ci/release.sh
    artifact_paths:
      - "release.txt"
      - "**/target/*"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'
