agents:
  provider: "gcp"
  image: "family/apm-agent-java-ubuntu-2204"

env:
  TARBALL_FILE: ${TARBALL_FILE:-artifacts.tar}

steps:
  - label: "Run the snapshot"
    key: "release"
    commands: .ci/snapshot.sh
    artifact_paths:
      - "snapshot.txt"
      - "**/target/*"
      - "${TARBALL_FILE}"

notify:
  - slack: "#apm-agent-java"
    # skip slack messages if no failures and dry-run mode
    if: 'build.state != "passed" && build.env("dry_run") == "false"'
