agents:
  provider: "gcp"
  #image: "family/apm-agent-java-ubuntu-2204"

steps:
  - label: "Run the snapshot"
    key: "release"
    commands: .ci/snapshot.sh
    artifact_paths:
      - "snapshot.txt"
      - "**/target/*"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'
