---

name: validate-tag
description: Validate tag format
    
inputs:
  tag:
    description: 'Tag to validate'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Validate tag does not exist on current commit
      id: validate-tag
      shell: 'bash'
      run: |
        if ! [ $(echo "${{ inputs.tag }}" | grep -P "(\d{1,2})\.(\d{1,2})\.(\d{1,2})") ]; then
          echo "Tag should be a SemVer format"
          exit 1
        fi
        if [ $(git tag -l "${{ inputs.tag }}") ]; then
          echo "The tag ${{ inputs.tag }} already exists"
          exit 1
        fi
