name: 'Build and publish docker images'
description: 'Builds and publishes the docker images for a given version using the agent artifact from maven central'
inputs:
  release_version:
    description: 'The version to release. If this is the currently latest version based on the git tags, it will also be published as latest'
    required: true
  ref:
    description: 'Branch or tag ref to run the action, defines the version of the scripts in the ./scripts folder to run'
    required: true
  dry_run:
    description: If set, generate the docker image but don't publish it
    required: true
  registry:
    description: 'The docker registry'
    required: true
  username:
    description: 'The docker username'
    required: true
  password:
    description: 'The docker password'
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to the Elastic Container registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: "Build docker image"
      shell: bash
      run: ./scripts/docker-release/build_docker.sh "${RELEASE_VERSION}"
      env:
        SONATYPE_FALLBACK: 1
        RELEASE_VERSION: ${{ inputs.release_version }}

    - name: "Push docker image"
      if: ${{ inputs.dry_run == 'false' }}
      shell: bash
      run: ./scripts/docker-release/push_docker.sh "${RELEASE_VERSION}"
      env:
        RELEASE_VERSION: ${{ inputs.release_version }}
