ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/java[elastic.co]
endif::[]

[[apis]]
== Programmatic APIs

There are three different ways enhance the out-of-the-box instrumentation of the Java agent with manual instrumentation:

. <<public-api>> +
  A simple and stable API that is most native to the agent.
  Contains annotations to declaratively create spans.
. <<opentelementry-bridge>> +
  A vendor neutral API.
  If you plan to do a lot of manual instrumentation and want to reduce vendor lock-in this is probably what you're looking for.
  Be aware that the API of 0.x versions is not stable.
  In this version, breaking changes are frequently introduced which means you may have to adapt your instrumentation code when updating.
. <<opentracing-bridge>> +
  A vendor neutral API that is discontinued in favor of OpenTelemetry.


include::./public-api.asciidoc[]
include::./opentelemetry.asciidoc[]
include::./opentracing.asciidoc[]
