ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/java[elastic.co]
endif::[]

[[intro]]

== Introduction

Welcome to the APM Java Agent documentation.

Elastic APM automatically measures the performance of your application and tracks errors.
For example, it records spans for database queries and transactions for incoming HTTP requests.
See <<supported-technologies>> to learn about which frameworks and technologies the Elastic APM Java agent supports out-of-the-box.

Spans are grouped in transactions - by default one for each incoming HTTP request.
But it's possible to create custom transactions not associated with an HTTP request.

By default the agent comes with support for common frameworks out-of-the-box.
To instrument other events,
you can use custom spans.
For information about custom spans,
see the <<public-api,public api documentation>>.

The agent is only one of multiple components you need to get started with APM.
Please also have a look at the documentation for

* {apm-server-ref}/index.html[APM Server]
* {ref}/index.html[Elasticsearch]

[float]
[[get-started]]
=== Get started

The first step in getting started with the Elastic APM Java agent is to download the latest release of the agent jar file from
link:https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:elastic-apm-agent[maven central].

NOTE: Don't declare a dependency to the agent in your application.

[float]
[[get-started-configuration]]
=== Configuration
Once you are set with instrumenting your favorite framework,
see the <<configuration,configuration guide>> on how to configure Elastic APM.

[float]
[[javaagent]]
=== Add `javaagent` flag
When starting your application, add the JVM flag `-javaagent:/path/to/elastic-apm-agent-<version>.jar`

[float]
[[spring-boot-javaagent]]
==== Add `javaagent` flag for a Spring Boot application

Start your spring application and add the `-javaagent` JVM flag:

[source,bash]
----
java -javaagent:/path/to/elastic-apm-agent-<version>.jar -jar my-spring-boot-application.jar
----

[float]
[[tomcat-javaagent]]
==== Add `javaagent` flag for Apache Tomcat
Create `$CATALINA_BASE/bin/setenv.sh` (or modify if the file already exists).

Add the following line:

[source,bash]
.setenv.sh
----
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:/path/to/elastic-apm-agent-<version>.jar"
----

[float]
[[supported-technologies]]
=== Supported technologies
Please check <<supported-technologies-details, the supported technologies page>>
whether the Elastic APM agent supports auto-instrumentation of the technologies your application is using.

