[[intro]]

== Introduction

Welcome to the APM Java Agent documentation.

Elastic APM automatically measures the performance of your application and tracks errors.
It records spans for database queries,
incoming HTTP requests,
and other slow operations that happen during requests to your app.

Spans are grouped in transactions - by default one for each incoming HTTP request.
But it's possible to create custom transactions not associated with an HTTP request.

By default the agent comes with support for common frameworks out-of-the-box.
To instrument other events,
you can use custom spans.
For information about custom spans,
see the link:public-api.asciidoc[public api documentation].

The agent is only one of multiple components you need to get started with APM.
Please also have a look at the documentation for

* https://www.elastic.co/guide/en/apm/server/current/index.html[APM Server]
* https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html[Elasticsearch]

[float]
[[get-started]]
=== Get started

The first step in getting started with the Elastic APM Java agent ist to download the latest release of the agent jar file from
link:http://mvnrepository.com/artifact/co.elastic.apm/apm-agent-java[maven central].

NOTE: Don't declare a dependency to the agent in your application.

[float]
[[configuration]]
=== Configuration
Once you are set with instrumenting your favorite framework,
see the link:configuration.asciidoc[configuration guide] on how to configure Elastic APM.

[float]
[[javaagent]]
=== Add `javaagent` flag
When starting your application, add the JVM flag `-javaagent:/path/to/apm-agent-java-<version>.jar`

[float]
[[supported-technologies]]
=== Supported technologies

|===
|Technology |Supported versions | Description

|Java
|Oracle and OpenJDK versions 7, 8 and 9
|

|JDBC
|4.1+
|The agent automatically creates DB spans for all your JDBC queries.
 This includes JDBC queries executed by O/R mappers like Hibernate.

|Servlet API
|3+
|A transaction will be created for all incoming HTTP requests to your Servlet API-based application.

|Spring MVC
|4+
|If you are using Spring MVC (for example with Spring Boot),
 the transactions are named based on your controllers (`ControllerClass#controllerMethod`).
|===

