ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/java[elastic.co]
endif::[]

[[intro]]
== Introduction

The Elastic APM Java Agent automatically measures the performance of your application and tracks errors.
It has built-in support for popular frameworks and technologies,
as well as a simple <<public-api,API>> which allows you to instrument any application.

NOTE: The minimum required version of the APM Server is 6.5.0

[float]
[[how-it-works]]
=== How does the Agent work?

The Agent auto-instruments <<supported-technologies>> and records interesting events,
like spans for database queries and transactions for incoming HTTP requests.
To do this, it leverages the capability of the JVM to instrument the bytecode of classes.
This means that for the supported technologies, there are no code changes required.

Spans are grouped in transactions -- by default, one for each incoming HTTP request.
But it's possible to create custom transactions not associated with an HTTP request.
Transactions and Spans are sent to the APM Server, where they're converted to a format suitable for Elasticsearch.
You can then use the APM app in Kibana to gain insight into latency issues and error culprits within your application.

More detailed information on how the Agent works can be found in the <<faq-how-does-it-work,FAQ>>.

[float]
[[experimental]]
=== Experimental features

Some agent features or <<supported-technologies-details,plugins>> are marked as `experimental`, which means:

* They are opt-in (disabled by default).
* There are no guarantees regarding changes in such features in future releases.
* In some cases they have special caveats or unknowns that come with them.
In such cases, the specific feature/plugin documentation should indicate that.

There are cases where we decide to release a feature as `experimental` to be on the safe side and only make it an official feature after we get some feedback about it.
Any such feedback will be highly appreciated, through a related GitHub issue or through the https://discuss.elastic.co/c/apm[APM discuss forum].

[float]
[[additional-components]]
=== Additional components

APM Agents work in conjunction with the {apm-server-ref-v}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
The {apm-overview-ref-v}/index.html[APM Overview] provides details on how these components work together,
and provides a matrix outlining {apm-overview-ref-v}/agent-server-compatibility.html[Agent and Server compatibility].
