ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/java[elastic.co]
endif::[]

[[intro]]

== Introduction

Welcome to the APM Java Agent documentation.

Elastic APM automatically measures the performance of your application and tracks errors.
For example, it records spans for database queries and transactions for incoming HTTP requests.
See <<supported-technologies>> to learn about which frameworks and technologies the Elastic APM Java agent supports out-of-the-box.

Spans are grouped in transactions - by default one for each incoming HTTP request.
But it's possible to create custom transactions not associated with an HTTP request.

By default the agent comes with support for common frameworks out-of-the-box.
To instrument other events,
you can use custom spans.
For information about custom spans,
see the <<public-api,public api documentation>>.

The agent is only one of multiple components you need to get started with APM.
Please also have a look at the documentation for

* {apm-server-ref}/index.html[APM Server]
* {ref}/index.html[Elasticsearch]

[float]
[[get-started]]
=== Get started

The first step in getting started with the Elastic APM Java agent ist to download the latest release of the agent jar file from
link:https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:elastic-apm-agent[maven central].

NOTE: Don't declare a dependency to the agent in your application.

[float]
[[get-started-configuration]]
=== Configuration
Once you are set with instrumenting your favorite framework,
see the <<configuration,configuration guide>> on how to configure Elastic APM.

[float]
[[javaagent]]
=== Add `javaagent` flag
When starting your application, add the JVM flag `-javaagent:/path/to/elastic-apm-agent-<version>.jar`

[float]
[[spring-boot-javaagent]]
==== Add `javaagent` flag for a Spring Boot application

Start your spring application and add the `-javaagent` JVM flag:

[source,bash]
----
java -javaagent:/path/to/elastic-apm-agent-<version>.jar -jar my-spring-boot-application.jar
----

[float]
[[tomcat-javaagent]]
==== Add `javaagent` flag for Apache Tomcat
Create `$CATALINA_BASE/bin/setenv.sh` (or modify if the file already exists).

Add the following line:

[source,bash]
.setenv.sh
----
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:/path/to/elastic-apm-agent-<version>.jar"
----

[float]
[[supported-technologies]]
=== Supported technologies
The Elastic APM Java agent automatically instruments various APIs,
frameworks and application servers.
This section lists all supported technologies.

If your favorite technology is not supported yet,
you can vote for it by participating in our
https://docs.google.com/forms/d/e/1FAIpQLScd0RYiwZGrEuxykYkv9z8Hl3exx_LKCtjsqEo1OWx8BkLrOQ/viewform?usp=sf_link[survey].
We will use the results to add support for the most requested technologies.

Another option is to get involved in the development of the agent.
See the https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md[contributing guide] for more details.

[float]
[[supported-java-versions]]
==== Java versions

|===
|Vendor |Supported versions

|Oracle JDK
|7, 8, 9, 10

|Open JDK
|7, 8, 9, 10

|IBM J9 VM
|8

|===


[float]
[[supported-apis]]
==== APIs
|===
|API |Supported versions | Description

|JDBC
|4.1+
|The agent automatically creates DB spans for all your JDBC queries.
 This includes JDBC queries executed by O/R mappers like Hibernate.

|Servlet API
|3+
|A transaction will be created for all incoming HTTP requests to your Servlet API-based application.

|===

[float]
[[supported-frameworks]]
==== Frameworks
|===
|Framework |Supported versions | Description


|Spring Web MVC
|4.x, 5.x
|If you are using Spring MVC (for example with Spring Boot),
  the transactions are named based on your controllers (`ControllerClass#controllerMethod`).

|Spring Boot
|1.5+, 2.x
|Supports embedded Tomcat, Jetty and Undertow

|===


[float]
[[supported-app-servers]]
==== Application Servers/Servlet Containers
The Elastic APM Java agent has generic support for the Servlet API 3+.
However, some servers require special handling.
The servers listed here are tested by an integration test suite to make sure Elastic APM is compatible with them.
Other Servlet 3+ compliant servers will most likely work as well.

|===
|Server |Supported versions

|Tomcat
|7.x, 8.5.x, 9.x

|WildFly
|8-13

|Jetty (only the `ServletContextHandler` is supported)
|9.2, 9.3, 9.4

|WebSphere
|8.5.5, 18.0.x

|Undertow Servlet
|1.4

|===
