ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/java[elastic.co]
endif::[]

[[public-api]]
== Public API
The public API of the Elastic APM Java agent lets you
customize and manually create spans and transactions,
as well as track errors.

The first step in getting started with the API is to declare a dependency to the API:

[source,xml]
.pom.xml
----
<dependency>
    <groupId>co.elastic.apm</groupId>
    <artifactId>apm-agent-api</artifactId>
    <version>${elastic-apm.version}</version>
</dependency>
----

[source,groovy]
.build.gradle
----
compile "co.elastic.apm:apm-agent-api:$elasticApmVersion"
----

Replace the version placeholders with the
link:https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:apm-agent-api[
latest version from maven central]:
image:https://img.shields.io/maven-central/v/co.elastic.apm/apm-agent-api.svg[Maven Central]

[float]
[[api-tracer-api]]
=== Tracer API
The tracer gives you access to the currently active transaction and span.
It can also be used to track an exception.

To use the API, you can just invoke the static methods on the class `co.elastic.apm.api.ElasticApm`.

[float]
[[api-current-transaction]]
==== `Transaction currentTransaction()`
Returns the currently active transaction.
See <<api-transaction>> on how to customize the current transaction.

If there is no current transaction,
this method will return a noop transaction,
which means that you never have to check for `null` values.

[source,java]
----
import co.elastic.apm.api.ElasticApm;
import co.elastic.apm.api.Transaction;

Transaction transaction = ElasticApm.currentTransaction();
----

NOTE: Transactions created via <<api-start-transaction, `ElasticApm.startTransaction()`>>
can not be retrieved by calling this method.
See <<api-span-activate, `span.activate()`>> on how to achieve that.

[float]
[[api-current-span]]
==== `Span currentSpan()`
Returns the currently active span or transaction.
See <<api-span>> on how to customize the current span.

If there is no current span,
this method will return a noop span,
which means that you never have to check for `null` values.

Note that even if this method is returning a noop span,
you can still <<api-span-capture-exception,capture exceptions>> on it.
These exceptions will not have a link to a Span or a Transaction.

[source,java]
----
import co.elastic.apm.api.ElasticApm;
import co.elastic.apm.api.Span;

Span span = ElasticApm.currentSpan();
----

NOTE: Spans created via <<api-span-start-span, `createSpan()`>>
can not be retrieved by calling this method.
See <<api-span-activate, `span.activate()`>> on how to achieve that.

[float]
[[api-start-transaction]]
==== `Transaction startTransaction()`
Use this method to create a custom transaction.


Note that the agent will do this for you automatically when ever your application receives an incoming HTTP request.
You only need to use this method to create custom transactions.

It is important to call <<api-transaction-end>> when the transaction has ended.
A best practice is to use the transaction in a try-catch-finally block.
Example:

[source,java]
----
Transaction transaction = ElasticApm.startTransaction();
try {
    transaction.setName("MyController#myAction");
    transaction.setType(Transaction.TYPE_REQUEST);
    // do your thing...
} catch (Exception e) {
    transaction.captureException(e);
    throw e;
} finally {
    transaction.end();
}
----

NOTE: Transactions created via this method can not be retrieved by calling <<api-current-span, `ElasticApm.currentSpan()`>>
or <<api-current-transaction, `ElasticApm.currentTransaction()`>>.
See <<api-transaction-activate, `transaction.activate()`>> on how to achieve that.

//----------------------------
[float]
[[api-transaction]]
=== Transaction API
//----------------------------
A transaction is the data captured by an agent representing an event occurring in a monitored service
and groups multiple spans in a logical group.
A transaction is the first <<api-span,`Span`>> of a service, and is also known under the term entry span.

See <<api-current-transaction>> on how to get a reference of the current transaction.

`Transaction` is a sub-type of `Span`.
So it has all the methods a <<api-span,`Span`>> offers plus additional ones.

NOTE: Calling any of the transaction's methods after <<api-transaction-end>> has been called is illegal.
You may only interact with transaction when you have control over its lifecycle.
For example, if a span is ended in another thread you must not add tags if there is a chance for a race between the <<api-transaction-end>>
and the <<api-transaction-add-tag>> method.

[float]
[[api-set-name]]
==== `void setName(String name)`
Override the name of the current transaction.
For supported frameworks,
the transaction name is determined automatically,
and can be overridden using this method.

Example:

[source,java]
----
transaction.setName("My Transaction");
----


* `name`: (required) A string describing name of the transaction

[float]
[[api-transaction-set-type]]
==== `void setType(String type)`
Sets the type of the transaction.
There’s a special type called `request`,
which is used by the agent for the transactions automatically created when an incoming HTTP request is detected.

Example:

[source,java]
----
transaction.setType(Transaction.TYPE_REQUEST);
----

* `type`: The type of the transaction

[float]
[[api-transaction-add-tag]]
==== `void addTag(String key, String value)`
A flat mapping of user-defined tags with string values.
Note: the tags are indexed in Elasticsearch so that they are searchable and aggregatable.
By all means,
you should avoid that user specified data,
like URL parameters,
is used as a tag key as it can lead to mapping explosions.

[source,java]
----
transaction.setTag("foo", "bar");
----

* `key`:   The tag key
* `value`: The tag value

[float]
[[api-transaction-set-user]]
==== `void setUser(String id, String email, String username)`
Call this to enrich collected performance data and errors with information about the user/client.
This method can be called at any point during the request/response life cycle (i.e. while a transaction is active).
The given context will be added to the active transaction.

If an error is captured, the context from the active transaction is used as context for the captured error.

[source,java]
----
transaction.setUser(user.getId(), user.getEmail(), user.getUsername());
----


* `id`:       The user's id or `null`, if not applicable.
* `email`:    The user's email address or `null`, if not applicable.
* `username`: The user's name or `null`, if not applicable.


[float]
[[api-transaction-capture-exception]]
==== `void captureException(Exception e)`
Captures an exception and reports it to the APM server.

[float]
[[api-transaction-get-id]]
==== `String getId()`
Returns the id of this transaction (never `null`)

If this transaction represents a noop,
this method returns an empty string.

[float]
[[api-transaction-get-trace-id]]
==== `String getTraceId()`
Returns the trace-id of this transaction.

The trace-id is consistent across all transactions and spans which belong to the same logical trace,
even for transactions and spans which happened in another service (given this service is also monitored by Elastic APM).

If this span represents a noop,
this method returns an empty string.

[float]
[[api-ensure-parent-id]]
==== `String ensureParentId()`
If the transaction does not have a parent-ID yet,
calling this method generates a new ID,
sets it as the parent-ID of this transaction,
and returns it as a `String`.

This enables the correlation of the spans the JavaScript Real User Monitoring (RUM) agent creates for the initial page load
with the transaction of the backend service.
If your backend service generates the HTML page dynamically,
initializing the JavaScript RUM agent with the value of this method allows analyzing the time spent in the browser vs in the backend services.

To enable the JavaScript RUM agent when using an HTML templating language like Freemarker,
add `ElasticApm.currentTransaction()` with the key `"transaction"` to the model.

Also, add a snippet similar to this to the body of your HTML page,
preferably before other JS libraries:

[source,html]
----
<script src="elastic-apm-js-base/dist/bundles/elastic-apm-js-base.umd.min.js"></script>
<script>
  var elasticApm = initApm({
    serviceName: '',
    serverUrl: 'http://localhost:8200',
    pageLoadTraceId: "${transaction.traceId}",
    pageLoadSpanId: "${transaction.ensureParentId()}",
    pageLoadSampled: ${transaction.sampled}
  })
</script>
----

See the {apm-rum-ref}[JavaScript RUM agent documentation] for more information.

[float]
[[api-transaction-start-span]]
==== `Span createSpan()`
Start and return a new custom span as a child of this transaction.

It is important to call <<api-span-end>> when the span has ended.
A best practice is to use the span in a try-catch-finally block.
Example:

[source,java]
----
Span span = parent.createSpan();
try {
    span.setName("SELECT FROM customer");
    span.setType("db.mysql.query");
    // do your thing...
} catch (Exception e) {
    ElasticApm.captureException(e);
    throw e;
} finally {
    span.end();
}
----

NOTE: Spans created via this method can not be retrieved by calling <<api-current-span, `ElasticApm.currentSpan()`>>.

[float]
[[api-transaction-end]]
==== `void end()`
Ends the transaction and schedules it to be reported to the APM Server.
It is illegal to call any methods on a span instance which has already ended.
This also includes this method and <<api-transaction-start-span>>.
Example:

[source,java]
----
transaction.end();
----

[float]
[[api-transaction-activate]]
==== `Scope activate()`
Makes this span the active span on the current thread until `Scope#close()` has been called.
Scopes should only be used in try-with-resource statements in order to make sure the `Scope#close()` method is called in all
circumstances.
Failing to close a scope can lead to memory leaks and corrupts the parent-child relationships.

This method should always be used within a try-with-resources statement:
[source,java]
----
Transaction transaction = ElasticApm.startTransaction();
// Within the try block the transaction is available
// on the current thread via ElasticApm.currentTransaction().
// This is also true for methods called within the try block.
try (final Scope scope = transaction.activate()) {
    transaction.setName("MyController#myAction");
    transaction.setType(Transaction.TYPE_REQUEST);
    // do your thing...
} catch (Exception e) {
    transaction.captureException(e);
    throw e;
} finally {
    transaction.end();
}
----

NOTE: <<api-transaction-activate>> and `Scope#close()` have to be called on the same thread.

//----------------------------
[float]
[[api-span]]
=== Span API
//----------------------------
A span contains information about a specific code path, executed as part of a transaction.

If for example a database query happens within a recorded transaction,
a span representing this database query may be created.
In such a case the name of the span will contain information about the query itself,
and the type will hold information about the database type.

See <<api-current-span>> on how to get a reference of the current span.

[float]
[[api-span-set-name]]
==== `void setName(String name)`
Override the name of the current span.

Example:

[source,java]
----
span.setName("SELECT FROM customer");
----

* `name`: the name of the span

[float]
[[api-span-set-type]]
==== `void setType(String type)`
Sets the type of span.
The type is a hierarchical string used to group similar spans together.
For instance, all spans of MySQL queries are given the type `db.mysql.query`.


In the above example `db` is considered the type prefix. Though there are no naming restrictions for this prefix,
the following are standardized across all Elastic APM agents: `app`, `db`, `cache`, `template`, and `ext`.

* `type`: the type of the span

[float]
[[api-span-add-tag]]
==== `void addTag(String key, String value)`
A flat mapping of user-defined tags with string values.
Note: the tags are indexed in Elasticsearch so that they are searchable and aggregatable.
By all means,
you should avoid that user specified data,
like URL parameters,
is used as a tag key as it can lead to mapping explosions.

[source,java]
----
span.setTag("foo", "bar");
----

* `key`:   The tag key
* `value`: The tag value

[float]
[[api-span-capture-exception]]
==== `void captureException(Exception e)`
Captures an exception and reports it to the APM server.

[float]
[[api-span-get-id]]
==== `String getId()`
Returns the id of this span (never `null`)

If this span represents a noop,
this method returns an empty string.

[float]
[[api-span-get-trace-id]]
==== `String getTraceId()`
Returns the trace-ID of this span.

The trace-ID is consistent across all transactions and spans which belong to the same logical trace,
even for transactions and spans which happened in another service (given this service is also monitored by Elastic APM).

If this span represents a noop,
this method returns an empty string.

[float]
[[api-span-end]]
==== `void end()`
Ends the span and schedules it to be reported to the APM Server.
It is illegal to call any methods on a span instance which has already ended.
This also includes this method and <<api-span-start-span>>.

[float]
[[api-span-start-span]]
==== `Span createSpan()`
Start and return a new custom span as a child of this span.

It is important to call <<api-span-end>> when the span has ended.
A best practice is to use the span in a try-catch-finally block.
Example:

[source,java]
----
Span span = parent.createSpan();
try {
    span.setName("SELECT FROM customer");
    span.setType("db.mysql.query");
    // do your thing...
} catch (Exception e) {
    span.captureException(e);
    throw e;
} finally {
    span.end();
}
----

NOTE: Spans created via this method can not be retrieved by calling <<api-current-span, `ElasticApm.currentSpan()`>>.
See <<api-span-activate, `span.activate()`>> on how to achieve that.

[float]
[[api-span-activate]]
==== `Scope activate()`
Makes this span the active span on the current thread until `Scope#close()` has been called.
Scopes should only be used in try-with-resource statements in order to make sure the `Scope#close()` method is called in all
circumstances.
Failing to close a scope can lead to memory leaks and corrupts the parent-child relationships.

This method should always be used within a try-with-resources statement:
[source,java]
----
Span span = parent.startSpan();
// Within the try block the span is available
// on the current thread via ElasticApm.currentSpan().
// This is also true for methods called within the try block.
try (final Scope scope = span.activate()) {
    span.setName("SELECT FROM customer");
    span.setType("db.mysql.query");
    // do your thing...
} catch (Exception e) {
    span.captureException(e);
    throw e;
} finally {
    span.end();
}
----

NOTE: Calling any of the span's methods after <<api-span-end>> has been called is illegal.
You may only interact with span when you have control over its lifecycle.
For example, if a span is ended in another thread you must not add tags if there is a chance for a race between the <<api-span-end>>
and the <<api-span-add-tag>> method.
