ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/java[elastic.co]
endif::[]

[[setup]]
== Set up the Agent

There are three different ways to set up the Elastic APM Java Agent:

. <<setup-javaagent>> +
  Manually set up and configure the agent with the `-javaagent` JVM option. No application code change required, requires
application restart.
. <<setup-attach-cli>> +
  Automatically set up the agent without needing to alter the configuration of your JVM or application server. No application code
  nor JVM options changes required, allows attaching to a running JVM.
. <<setup-attach-api>> +
  Set up the agent with a one-line code change and an extra `apm-agent-attach` dependency. No modification of JVM options,
  the agent artifact is embedded within the packaged application binary.

[float]
[[get-started-configuration]]
=== Configuration

Once you've set up the Agent, see the <<configuration,configuration guide>> on how to configure Elastic APM.

[float]
[[ssl-setup]]
=== SSL/TLS communication with APM Server

If {apm-guide-ref}/agent-tls.html[SSL/TLS communication] is enabled on the APM Server, make sure to check out the <<ssl-configuration, SSL setup guide>>.

[float]
[[aws-lambda-setup]]
=== Monitoring AWS Lambda Functions (Experimental)

Learn how to set up AWS Lambda functions tracing in our <<aws-lambda, Lambda setup guide>>.

[float]
[[security-manager]]
=== Using with Security Manager enabled

The agent should work as expected on JVMs with an enabled `SecurityManager`, provided that it is granted with `java.security.AllPermission`.
Make sure that the following snippet is added to an effective* policy (replace with the real path** to the agent jar):
```
grant codeBase "file:</path/to/elastic-apm-agent.jar>" {
    permission java.security.AllPermission;
};
```
If you see a `java.lang.SecurityException` exception (for example a - `java.security.AccessControlException`) after verifying the above
`grant` snippet is effectively applied, open an issue in our https://github.com/elastic/apm-agent-java[GitHub repo] with a description
and the full stack trace.

{empty}* it is possible to have multiple policy files taking effect at the same time on a single JVM. The policy entry above can be added
to an existing policy or can be appended through the `java.security.policy` system property. See
https://docs.oracle.com/javase/8/docs/technotes/guides/security/PolicyFiles.html[documentation] for more details.

{empty}** you can make use of the https://docs.oracle.com/javase/8/docs/technotes/guides/security/PolicyFiles.html#PropertyExp[property
expansion] capability for specifying the agent jar path.

[float]
[[supported-technologies]]
=== Supported technologies

Please check <<supported-technologies-details,supported technologies>>
for details on if the Elastic APM agent supports auto-instrumentation of the technologies your application is using.

include::./setup-javaagent.asciidoc[]
include::./setup-attach-cli.asciidoc[]
include::./setup-attach-api.asciidoc[]
include::./setup-ssl.asciidoc[Set up SSL]
include::./setup-aws-lambda.asciidoc[AWS Lambda monitoring]
