[[setup-javaagent]]
=== Manual setup with `--javaagent` flag

[float]
[[setup-javaagent-download]]
==== Download the Java agent

The first step in getting started with the Elastic APM Java agent is to download the latest release of the agent jar file from
link:https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:elastic-apm-agent[maven central].

NOTE: Don't declare a dependency to the agent in your application.

[float]
[[setup-javaagent-add-flag]]
==== Add `javaagent` flag
When starting your application, add the JVM flag `-javaagent:/path/to/elastic-apm-agent-<version>.jar`

[float]
[[application-server-setup]]
=== Set up the agent with Application Servers
Different application servers have different ways of setting the `-javaagent` flag and system properties.

Note that system properties are only one way of configuring the agent but setting the `-javaagent` flag is required in each case.
See <<configuration>> to learn about how to configure the agent with a configuration file or environment variables.

[float]
[[setup-generic]]
==== Generic Setup
Start your application (for example a Spring Boot application or other embedded servers) and add the `-javaagent` JVM flag.
Use the `-D` prefix to configure the agent using system properties.

[source,bash]
----
java -javaagent:/path/to/elastic-apm-agent-<version>.jar -Delastic.apm.service_name=my-cool-service -Delastic.apm.application_packages=org.example,org.another.example -Delastic.apm.server_urls=http://localhost:8200 -jar my-application.jar
----

[float]
[[setup-tomcat]]
==== Apache Tomcat

[float]
[[setup-tomcat-unix]]
===== Unix
Create `bin/setenv.sh` (or modify if the file already exists).
Make sure to make the file executable, for example `chmod +x bin/setenv.sh`

Add the following line:

[source,bash]
.setenv.sh
----
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:/path/to/elastic-apm-agent-<version>.jar"
export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.service_name=my-cool-service"
export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.application_packages=org.example,org.another.example"
export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.server_urls=http://localhost:8200"
----

[float]
[[setup-tomcat-windows]]
===== Windows
Create `bin\setenv.bat` (or modify if the file already exists).

[source,batch]
.setenv.bat
----
set CATALINA_OPTS=%CATALINA_OPTS% -javaagent:C:/path/to/elastic-apm-agent-<version>.jar
set CATALINA_OPTS=%CATALINA_OPTS% -Delastic.apm.service_name=my-cool-service
set CATALINA_OPTS=%CATALINA_OPTS% -Delastic.apm.application_packages=org.example,org.another.example
set CATALINA_OPTS=%CATALINA_OPTS% -Delastic.apm.server_urls=http://localhost:8200
----

[float]
[[setup-jetty]]
==== Jetty

Option 1: edit `jetty.sh`

[source,bash]
.jetty.sh
----
export JAVA_OPTIONS="${JAVA_OPTIONS} -javaagent:/path/to/elastic-apm-agent-<version>.jar"
export JAVA_OPTIONS="${JAVA_OPTIONS} -Delastic.apm.service_name=my-cool-service"
export JAVA_OPTIONS="${JAVA_OPTIONS} -Delastic.apm.application_packages=org.example,org.another.example"
export JAVA_OPTIONS="${JAVA_OPTIONS} -Delastic.apm.server_urls=http://localhost:8200"
----

Option 2: edit `start.ini`

[source,ini]
.start.ini
----
--exec
-javaagent:/path/to/elastic-apm-agent-<version>.jar
-Delastic.apm.service_name=my-cool-service
-Delastic.apm.application_packages=org.example,org.another.example
-Delastic.apm.server_urls=http://localhost:8200
----

Option 3: If you are using embedded Jetty, see <<setup-generic>>.

[float]
[[setup-jboss-wildfly]]
==== JBoss EAP/WildFly

[float]
[[setup-jboss-wildfly-standalone]]
===== Standalone Mode
Add the agent configuration at the bottom of the `standalone.conf` file:

**Unix**

[source,bash]
.bin/standalone.conf
----
export JAVA_OPTS="$JAVA_OPTS -javaagent:/path/to/elastic-apm-agent-<version>.jar"
export JAVA_OPTS="$JAVA_OPTS -Delastic.apm.service_name=my-cool-service"
export JAVA_OPTS="$JAVA_OPTS -Delastic.apm.application_packages=org.example,org.another.example"
export JAVA_OPTS="$JAVA_OPTS -Delastic.apm.server_urls=http://localhost:8200"
----

**Windows**

[source,bash]
.bin/standalone.conf.bat
----
set JAVA_OPTS=%JAVA_OPTS% -javaagent:C:/path/to/elastic-apm-agent-<version>.jar
set JAVA_OPTS=%JAVA_OPTS% -Delastic.apm.service_name=my-cool-service
set JAVA_OPTS=%JAVA_OPTS% -Delastic.apm.application_packages=org.example,org.another.example
set JAVA_OPTS=%JAVA_OPTS% -Delastic.apm.server_urls=http://localhost:8200
----

[float]
[[setup-jboss-wildfly-domain]]
===== Domain Mode
Edit the `domain.xml` file which is usually located under `domain/configuration` and add a JVM option for the `-javaagent` flag,
as well as some system properties for the configuration.

[source,xml]
.domain/configuration/domain.xml
----
...
<server-group>
  <jvm>
     <jvm-options>
      ...
      <option value="-javaagent:/path/to/elastic-apm-agent-<version>.jar"/>
      ...
     </jvm-options>
  </jvm>
</server-group>
...
<system-properties>
  <property name="elastic.apm.service_name"         value="my-cool-service"/>
  <property name="elastic.apm.application_packages" value="org.example,org.another.example"/>
  <property name="elastic.apm.server_urls"          value="http://localhost:8200"/>
</system-properties>
...
----

[float]
[[setup-websphere-liberty]]
==== WebSphere Liberty
Add the following lines to the `jvm.options` file.

[source,options]
.jvm.options
----
-javaagent:/path/to/elastic-apm-agent-<version>.jar
-Delastic.apm.service_name=my-cool-service
-Delastic.apm.application_packages=org.example,org.another.example
-Delastic.apm.server_urls=http://localhost:8200
----

[float]
[[setup-payara]]
==== Payara
Update the `domain.xml` file to add the `-javaagent` flag and system properties.

[source,xml]
.glassfish/domains/domain1/config/domain.xml
----
<java-config>
  ...
  <jvm-options>-javaagent:/path/to/elastic-apm-agent-<version>.jar</jvm-options>
  <jvm-options>-Delastic.apm.service_name=my-cool-service</jvm-options>
  <jvm-options>-Delastic.apm.application_packages=org.example,org.another.example</jvm-options>
  <jvm-options>-Delastic.apm.server_urls=http://localhost:8200</jvm-options>
</java-config>
----

[float]
[[setup-weblogic]]
==== Oracle WebLogic

[float]
[[setup-weblogic-unix]]
===== Unix
Edit the `startWebLogic.sh` file and add the following lines after the `setDomainEnv.sh` call:

[source,bash]
.$DOMAIN_HOME/bin/startWebLogic.sh
----
export JAVA_OPTIONS="$JAVA_OPTIONS -javaagent:/path/to/elastic-apm-agent-<version>.jar"
export JAVA_OPTIONS="$JAVA_OPTIONS -Delastic.apm.service_name=my-cool-service"
export JAVA_OPTIONS="$JAVA_OPTIONS -Delastic.apm.application_packages=org.example,org.another.example"
export JAVA_OPTIONS="$JAVA_OPTIONS -Delastic.apm.server_urls=http://localhost:8200"
----

[float]
[[setup-weblogic-windows]]
===== Windows
Edit the `startWebLogic.cmd` file and add the following lines after the `setDomainEnv.cmd` call:

[source,batch]
.%DOMAIN_HOME%\bin\startWebLogic.cmd
----
set JAVA_OPTIONS=%JAVA_OPTIONS% -javaagent:C:/path/to/elastic-apm-agent-<version>.jar
set JAVA_OPTIONS=%JAVA_OPTIONS% -Delastic.apm.service_name=my-cool-service
set JAVA_OPTIONS=%JAVA_OPTIONS% -Delastic.apm.application_packages=org.example,org.another.example
set JAVA_OPTIONS=%JAVA_OPTIONS% -Delastic.apm.server_urls=http://localhost:8200
----

[float]
[[setup-cloud-foundry]]
==== Cloud Foundry
The Elastic Java APM Agent Framework is now part of the Cloud Foundry Java Buildpack as of link:https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.19[Release v4.19].

A user provided Elastic APM service must have a name or tag with `elastic-apm` in it so that the Elastic APM Agent Framework will automatically configure the application to work with the service.

Create a user provided service:

`cf cups my-elastic-apm-service -p '{"server_urls":"https://my-apm-server:8200","secret_token":"my-secret-token"}'`

Bind the application to the service:

`cf bind-service my-application my-elastic-apm-service`

or use the `services` block in the application manifest file.

For more details on the Elastic Java APM Agent Framework for Cloud Foundry see link:https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-elastic_apm_agent.md[here].

[source,yml]
.manifest.yml
----
applications:
- name: my-application
  memory: 1G
  path: ./target/my-application.jar
  services:
    - my-elastic-apm-service
----
