[[upgrading]]
== Upgrading

Upgrades between minor versions of the agent, like from 1.1 to 1.2 are always backwards compatible.
Upgrades that involve a major version bump often come with some backwards incompatible changes.

Before upgrading the agent, be sure to review the:

* <<release-notes,Agent release notes>>
* {apm-guide-ref}/agent-server-compatibility.html[Agent and Server compatibility chart]

[float]
[[upgrade-steps]]
=== Recommended upgrade steps

. Shut down the application.
. Download the latest release of the agent jar file from
https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:elastic-apm-agent[maven central].
. Optionally change JVM settings, e.g., if the path to the agent jar has changed due to a different file name.
. Restart the application.

[float]
[[end-of-life-dates]]
=== End of life dates

We love all our products, but sometimes we must say goodbye to a release so that we can continue moving
forward on future development and innovation.
Our https://www.elastic.co/support/eol[End of life policy] defines how long a given release is considered supported,
as well as how long a release is considered still in active development or maintenance.
