[[upgrading]]
== Upgrading
Upgrades between minor versions of the agent, like from 1.1 to 1.2 are always backwards compatible.
Upgrades that involve a major version bump often come with some backwards incompatible changes.

Before upgrading the agent, be sure to review the:

* <<release-notes,Agent release notes>>
* {apm-overview-ref-v}/agent-server-compatibility.html[Agent and Server compatibility chart]

[float]
[[end-of-life-dates]]
=== End of life dates

We love all our products, but sometimes we must say goodbye to a release so that we can continue moving
forward on future development and innovation.
Our https://www.elastic.co/support/eol[End of life policy] defines how long a given release is considered supported,
as well as how long a release is considered still in active development or maintenance.
The table below is a simplified description of this policy.

[options="header"]
|====
|Agent version |EOL Date |Maintained until
|1.13.x |2021-08-11 |1.14.0
|1.12.x |2021-05-21 |1.13.0
|1.11.x |2021-04-31 |1.12.0
|1.10.x |2021-03-30 |1.11.0
|1.9.x |2021-02-22 |1.10.0
|1.8.x |2021-01-30 |1.9.0
|1.7.x |2020-12-13 |1.8.0
|1.6.x |2020-10-16 |1.7.0
|1.5.x |2020-09-26 |1.6.0
|1.4.x |2020-08-14 |1.5.0
|1.3.x |2020-07-10 |1.4.0
|1.2.x |2020-06-19 |1.3.0
|1.1.x |2020-05-28 |1.2.0
|1.0.x |2020-05-14 |1.1.0
|====
