name: daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  pull_request:

permissions:
  actions: write

jobs:
  run-jdk-compatibility-and-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'elastic',
              repo: 'apm-agent-java',
              workflow_id: 'main.yml',
              ref: 'master',
              inputs: {"jdk_compatibility_ci": "true", "windows_ci": "true"}
            })
