name: microbenchmark

on:
  workflow_dispatch:
    inputs:
      stack_version:
        description: "JVM, use values from: curl -s https://jvm-catalog.elastic.co/jdks/tags/linux,x86_64 | jq '.[] | .id'"
        default: 'openjdk-17+35-linux'
        required: false
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.asciidoc'

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  microbenchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run microbenchmark
        uses: elastic/oblt-actions/buildkite/run@v1.5.0
        env:
          JAVA_VERSION: ${{ inputs.java_version || 'openjdk-17+35-linux' }}
        with:
          pipeline: "apm-agent-microbenchmark"
          token: ${{ secrets.BUILDKITE_TOKEN }}
          wait-for: false
          env-vars: |
            script=.ci/scripts/bench.sh
            repo=apm-agent-java
            sha=${{ github.sha }}
            JAVA_VERSION=${{ env.JAVA_VERSION }}
            BRANCH_NAME=${{ github.ref_name }}
