---

name: Pre release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag ref to run the workflow on'
        required: true
        default: "main"
      version:
        description: 'The version to release (e.g. 1.2.3). This workflow will automatically perform the required version bumps'
        required: true

permissions:
  contents: read
      
concurrency:
  group: ${{ github.workflow }}
      
jobs:
  pre-release:
    name: "Bump versions and create PR"
    uses: ./.github/workflows/pre-post-release.yml
    permissions:
      contents: write
    with:
      ref: ${{ inputs.ref }}
      version: ${{ inputs.version }}
      phase: 'pre'
    secrets: inherit
