name: sonarqube

## TODO: run on branches initially
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.asciidoc'

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/vault-action@v2.4.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/observability-team/ci/sonarqube/apm-agent-java sonar-token | SONAR_TOKEN ;
            secret/observability-team/ci/sonarqube/apm-agent-java sonar-host-url | SONAR_HOST_URL ;
            secret/observability-team/ci/sonarqube/apm-agent-java project-key | SONAR_PROJECT_KEY

      - uses: ./.github/workflows/maven-goal
        with:
          command: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true
      - name: mvn sonar
        run: |-
          ./mvnw verify -P ci-non-application-server-integration-tests \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey="${{ env.SONAR_PROJECT_KEY }}" \
            -Dsonar.login=${{ env.SONAR_TOKEN }} \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
