---
## Workflow to process the JUnit test results and add a report to the checks.
name: test-reporter
on:
  workflow_run:
    workflows:
      - main
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/test-report@current
        with:
          artifact: /test-results-(.*)/
          name: 'Test Results $1'
          path: "**/*.xml"                  # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
