name: tmp-test

on: pull_request

jobs:
  tmp-test:
    runs-on: ubuntu-latest
    steps:
      - id: buildkite
        name: Run Deploy
        uses: reakaleek/apm-pipeline-library/.github/actions/buildkite@feature/buildkite-download-artifacts
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: apm-agent-java-release
          pipelineVersion: ${{ inputs.version }}
          waitFor: true
          printBuildLogs: true
          artifactName: lambda-zip
          artifactPath: "elastic-apm-agent/target/**/elastic-apm-java-aws-lambda-layer-*.zip"
          buildEnvVars: |
            dry_run=true
