name: "Trigger Tests"
on:
  pull_request_target:
    types: [opened, ready_for_review]
env:
  MY_GITHUB_TOKEN: ${{ secrets.APM_TECH_USER_TOKEN }}

jobs:
  triggerCI:
    runs-on: ubuntu-latest
    steps:
    if: ${{ !github.event.pull_request.draft }}
    - name: Add comment to trigger tests
      uses: wow-actions/auto-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pullRequestOpened: /test

